package com.github.se.cyrcle.model.parking

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Query
import androidx.room.Upsert

/**
 * Data access object for tiles It serves as an intermediary between the database and the repository
 *
 * It is not implemented in this project as it is auto generated by Room during compilation Getters
 * are written in SQLite as string within the query annotation
 */
@Dao
interface TileDao {

  /**
   * Insert or update a tile (depending if it is already present in the database)
   *
   * @param tile the tile to insert or update
   */
  @Upsert suspend fun upsert(tile: Tile)

  /**
   * Delete a tile
   *
   * @param tile the tile to delete
   */
  @Delete suspend fun delete(tile: Tile)

  /**
   * Get all tiles
   *
   * @return a list of all tiles
   */
  @Query("SELECT * FROM tiles") suspend fun getAllTiles(): List<Tile>

  /**
   * Get a tile by its identifier
   *
   * @param uid the identifier of the tile
   * @return the tile with the given identifier
   */
  @Query("SELECT * FROM tiles WHERE uid = :uid") suspend fun getTile(uid: String): Tile
}
