package com.github.se.cyrcle.model.parking.offline

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Query
import androidx.room.Upsert
import com.github.se.cyrcle.model.parking.Parking
import com.github.se.cyrcle.model.parking.Tile
import org.jetbrains.annotations.TestOnly

/**
 * Data access object for parkings. It serves as an intermediary between the database and the
 * repository
 *
 * It is not implemented in this project as it is auto generated by Room during compilation. Getters
 * are written in SQLite as string within the query annotation
 */
@Dao
interface ParkingDao {

  /**
   * Insert or update a parking
   *
   * @param parking the parking to insert or update
   */
  @Upsert suspend fun upsert(parking: Parking)

  /**
   * Insert or update a list of parkings
   *
   * @param parkings the list of parkings to insert or update
   */
  @Upsert suspend fun upsertAll(parkings: List<Parking>)

  /**
   * Delete a parking y it's uid
   *
   * @param uid the parking id to delete
   */
  @Query("DELETE FROM ${Parking.TABLE_NAME} WHERE uid = :uid ") suspend fun delete(uid: String)

  /**
   * Deletes parkings whose UIDs are in the list
   *
   * @param uids the list of UIDs of parkings to delete
   */
  @Query("DELETE FROM ${Parking.TABLE_NAME} WHERE uid IN (:uids) ")
  suspend fun deleteAll(uids: List<String>)

  /**
   * Deletes parkings present in the given tiles
   *
   * @param tiles the list of Tiles to delete
   */
  @Query("DELETE FROM ${Parking.TABLE_NAME} WHERE tile IN (:tiles) ")
  suspend fun deleteAllInTiles(tiles: Set<Tile>)

  /**
   * Delete a parking
   *
   * @param parking the parking to delete
   */
  @Delete suspend fun delete(parking: Parking)

  /**
   * Get a parking by its identifier
   *
   * @param uid the identifier of the tile
   * @return the tile with the given identifier
   */
  @Query("SELECT * FROM ${Parking.TABLE_NAME} WHERE uid = :uid")
  suspend fun getParking(uid: String): Parking?

  /**
   * Get a list of parkings
   *
   * @param uids the queried parkings
   * @return The queried parkings
   */
  @Query("SELECT * FROM ${Parking.TABLE_NAME} WHERE uid IN (:uids)")
  suspend fun getParkings(uids: List<String>): List<Parking>

  /**
   * Get a list of parkings belonging to the tile
   *
   * @param tile the queried tile
   * @return The parkings belonging to the tile
   */
  @Query("SELECT * FROM ${Parking.TABLE_NAME} WHERE tile = :tile")
  suspend fun getParkingsInTile(tile: Tile): List<Parking>

  /**
   * Get all parkings Only to be used for testing!
   *
   * @return All parkings in the database
   */
  @TestOnly
  @Query("SELECT * FROM ${Parking.TABLE_NAME}")
  suspend fun getAllParkings(): List<Parking>
}
