package com.github.se.cyrcle.model.parking.offline

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import com.github.se.cyrcle.io.serializer.ParkingSetAdapter
import com.github.se.cyrcle.io.serializer.PointAdapter
import com.github.se.cyrcle.model.parking.Tile

/**
 * Database for tiles It is used to store tiles in the local database
 *
 * As for the DAO, it is not implemented in this project since it is auto generated by Room during
 * compilation
 */
@Database(entities = [Tile::class], version = 1)
@TypeConverters(PointAdapter::class, ParkingSetAdapter::class)
abstract class TileDatabase : RoomDatabase() {

  /** DAO generated by Room */
  abstract val tileDao: TileDao

  companion object {
    /** Database name */
    const val DB_NAME = "tile_database"
  }
}
